package ru.eltech.services;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.eltech.config.TasksConfig;
import ru.eltech.entity.Room;
import ru.eltech.entity.Task;
import ru.eltech.repositories.RoomRepository;
import ru.eltech.repositories.TaskRepository;
import java.time.LocalDate;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class TaskGeneratorService {

    private final TasksConfig tasksConfig;
    private final RoomRepository roomRepository;
    private final TaskRepository taskRepository;

    @Transactional
    public void ensureTasksOnStartup() {
        log.info("Гарантируем задачи на неделю вперед...");

        LocalDate today = LocalDate.now();

        for (int i = 0; i <= tasksConfig.getDaysAhead(); i++) {
            LocalDate date = today.plusDays(i);

            if (taskRepository.countByTaskDate(date) == 0) {
                log.info("Создаем задачи на: {}", date);
                generateTasksForDate(date);
            }
        }
    }

    @Scheduled(cron = "0 1 0 * * *")
    @Transactional
    public void nightlyGeneration() {
        log.info("Ночная генерация...");
        generateTasksForDate(LocalDate.now().plusDays(1));
    }

    @Transactional
    public void generateTasksForDate(LocalDate date) {
        List<Room> allRooms = roomRepository.findAll();
        List<TasksConfig.TaskTemplate> templates = tasksConfig.getTemplates();

        // Для каждой комнаты создаем ВСЕ задачи из шаблонов
        for (Room room : allRooms) {
            for (TasksConfig.TaskTemplate template : templates) {
                createTask(template, room, date);
            }
        }
    }

    private void createTask(TasksConfig.TaskTemplate template,
                            Room room, LocalDate date) {
        Task task = new Task();
        task.setTitle(template.getTitle());
        task.setDescription(template.getDescription());
        task.setTaskDate(date);
        task.setRoom(room);
        task.setIsCompleted(false);
        task.setIsAutoGenerated(true);

        taskRepository.save(task);
    }
}