package ru.eltech.services;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.eltech.config.TasksConfig;
import ru.eltech.entity.Room;
import ru.eltech.entity.Task;
import ru.eltech.repositories.RoomRepository;
import ru.eltech.repositories.TaskRepository;
import java.time.LocalDate;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class TaskGeneratorService {

    private final TasksConfig tasksConfig;
    private final RoomRepository roomRepository;
    private final TaskRepository taskRepository;

    @PostConstruct  // Выполняется при запуске приложения
    @Transactional
    public void init() {
        ensureTasksForWeekAhead();
    }

    @Scheduled(cron = "0 1 0 * * *")  // Каждый день в 00:01
    @Transactional
    public void dailyTasksGeneration() {
        ensureTasksForWeekAhead();
    }

    @Transactional
    public void ensureTasksForWeekAhead() {
        log.info("Обеспечиваем задачи на неделю вперед...");

        LocalDate today = LocalDate.now();
        LocalDate endDate = today.plusDays(tasksConfig.getDaysAhead());

        // Проходим по всем дням от сегодня до endDate
        for (LocalDate date = today; !date.isAfter(endDate); date = date.plusDays(1)) {
            ensureTasksForDate(date);
        }
    }

    private void ensureTasksForDate(LocalDate date) {
        // Проверяем, есть ли хоть одна задача на эту дату
        if (taskRepository.countByTaskDate(date) != 0) {
            log.debug("Задачи на {} уже существуют", date);
            return;
        }

        log.info("Создаем задачи на: {}", date);
        generateTasksForDate(date);
    }

    public void generateTasksForDate(LocalDate date) {
        List<Room> allRooms = roomRepository.findAll();
        List<TasksConfig.TaskTemplate> templates = tasksConfig.getTemplates();

        for (Room room : allRooms) {
            for (TasksConfig.TaskTemplate template : templates) {
                createTask(template, room, date);
            }
        }

        log.info("Создано {} задач на {}",
                allRooms.size() * templates.size(), date);
    }

    private void createTask(TasksConfig.TaskTemplate template,
                            Room room, LocalDate date) {
        Task task = new Task();
        task.setTitle(template.getTitle());
        task.setDescription(template.getDescription());
        task.setTaskDate(date);
        task.setRoom(room);
        task.setIsCompleted(false);
        task.setIsAutoGenerated(true);

        taskRepository.save(task);
    }
}